const aminoAcidsString = "MMMASKDAPTS.DGASGAGQLVPEANTAEPI.MDPVAGASTAVATAGQVNMIDPWI.NNFVQAPQGEFTISPNNTPGDILFDLQLGPHLNPFL.HLSQMYNGWVGNMRVRILLAGNAFTAGKIIICCVPPGF.A.N.TIAQATLFPHVIADVRTLEPIE.PLEDVRNVLFHNN..N.PTMRLVCMLYTPLRTGG.S.GTD.FVVAGRVLTCPSPDFSFLFLVPP.VEQKTR.FSVPN.PL..LSNSRVP..I..M..SPD..Q.VQFQNGRCT.DGQL.GTTP.SLSQLCKIRG.....S.G.V.NLSELDGSPFHPFESPAPVGFPDLG.CDWH.......Q............T....FVPHLGSI...........GD..G.L.WIS.PS.......N.W.IP.YGSS.TE..HLAP.VYPPGFGE.IVYFMS.FPG.G......VPCLLPQEFI.HF.NEQAP..GEAALLHYVDPDTGRNLGEFKLYPDGF.TCVPN..S.GPQ.LPINGVFVFVSWVSRFYQLKPVGTAS.ARRLG.RR.";

// Split the amino acids by the '.' symbol
const aminoAcidsArray = aminoAcidsString.split('.');

// Filter and print elements with length 9 or more
const resultNineToFourteen = aminoAcidsArray.filter(sequence => sequence.length >= 9 && sequence.length < 15);
console.log('Protein #1')
console.table(resultNineToFourteen);

const resultSixteenUp = aminoAcidsArray.filter(sequence => sequence.length >= 16);
console.table(resultSixteenUp);

const resultFifteen = aminoAcidsArray.filter(sequence => sequence.length === 15);
console.table(resultFifteen);

const aminoAcidsString2 = "MKMAS.DA.PS.DGAANLVPE.N.E.LALEPVAG..IAAPV.GQ.NIIDPWI..NFVQAP.GEFTVSPRNSPGE.L..LELGP.LNPYL.HLARMYNGYAGG.EVQV.LAGNAFTAGK..FAAVPP.FP...ISP.Q.TM.PH.IVDVRQLEPV.LPLPDVRN.FFHY.Q...P.MRLVAMLYTPLR.N.SGDDVFTVSCRVLTRP.PDF.F.FLVPPTVESKTKPFTLP.L...EMTNSRFP..I..L.T.P.....VQ.QNGRCT.DG.LQGTT......IC...G......................M.....NG..F.P....PAPLG.PDF.G.I.G...Q..............R...A...T....F.P..G...................FTP.G...........Q..LP.Y.G.......LAP.VAP.FPGE.ILFFRS..P...G.....IDCL.PQEWVQHFY.E.AP.QS.VAL.RY.NPDTGR..FE.KLHR.GF.TV.........VP.NG.FRFD.WVN.FYTL.PMGTG.GRRR.....";


const aminoAcidsArray2 = aminoAcidsString2.split('.');


const resultNineToFourteen2 = aminoAcidsArray2.filter(sequence => sequence.length >= 9 && sequence.length < 15);
console.log('Protein #2')
console.table(resultNineToFourteen2);

const resultSixteenUp2 = aminoAcidsArray2.filter(sequence => sequence.length >= 16);
console.table(resultSixteenUp2);

const resultFifteen2 = aminoAcidsArray2.filter(sequence => sequence.length === 15);
console.table(resultFifteen2);

const aminoAcidsString3 = "MKMASSDA.PSSDGAGNLVPESQQEVLPLAPVAGAALAAPVVGQTNIIDPWIKENFVQAPQGEFTVSPKNSPGEILVNLELGP.LNPYLDHLSRMYNAYAGGIEVEIILAGNAFTAGKVLIAAVPPNFPVE.VSASQATQFPHVIVDVRTLEPVRLPLPDVRSNFFHYTT..EPKMRLVIWLYTPLRTNGSGDDSFTVSGRILTRPS.DFEFSFLVPPTVETKTV.FSVPGL.VQEMSNSRWPAQISGMVVRGNEPQVVQFQNGRCHTDGTLLGTTTVS.N.IAG.RG.ST...S..G...TE.R.GDTDLWLRLEEPDGQPYDIFGDQPAPLGTPDF.AVIVGFA.RP.TSGSY.NEAYVNTTDSDFAPATGNTKI.LR.GGTGHVG.GHYW.FRPFGVEGG..R.QYQEY.LPDYSG.TASNHNLAPPVAPRMPGELLLLFESDMPVWDDGHGAAPAQKIHCLLPQEFITHFFD.QAPALAEAALLRYVHPDS.RVLFECKLYREGYMVVAAP.GRLDFPLDGYFRFDSWVSSFYILSPVGSGQGRRGRSK..";


const aminoAcidsArray3 = aminoAcidsString3.split('.');


const resultNineToFourteen3 = aminoAcidsArray3.filter(sequence => sequence.length >= 9 && sequence.length < 15);
console.log('Protein #3')
console.table(resultNineToFourteen3);

const resultSixteenUp3 = aminoAcidsArray3.filter(sequence => sequence.length >= 16);
console.table(resultSixteenUp3);

const resultFifteen3 = aminoAcidsArray3.filter(sequence => sequence.length === 15);
console.table(resultFifteen3);

const aminoAcidsString4 = "MAQAI.GAIAASAAGSALGAGIQAG.EAALQ.QRYQQDLQLQ.NSFKHD.EM.GYQV.ASNALLAKNL.TRY.LL...GLSSADAAR.VAGAPVTRIVDWNGTRIAAP.SSATTLRSGGFM.VP.....K..KQ...SG.SNPNY..S...SRT.SWV.SQNS.R..L.PFH..ALRTVWVTPPGSTSTST.SSV.....FNTDRLPLFANRR.";


const aminoAcidsArray4 = aminoAcidsString4.split('.');


const resultNineToFourteen4 = aminoAcidsArray4.filter(sequence => sequence.length >= 9 && sequence.length < 15);
console.log('Protein #4')
console.table(resultNineToFourteen4);

const resultSixteenUp4 = aminoAcidsArray4.filter(sequence => sequence.length >= 16);
console.table(resultSixteenUp4);

const resultFifteen4 = aminoAcidsArray4.filter(sequence => sequence.length === 15);
console.table(resultFifteen4);

const aminoAcidsString5 = "MAGAF.AGL..D....GVGSLI.AGA.AINQK.EFE.N..LQ..SF.HDKEML.AQI.ATK.LQ..MM..K...L..GGFSPTDAARGAVNAPMTK.LDWNGTRYWAP.A..TT..SG.F.............................S..S.........T....S..G.....S..........S......RT..WV..Q...L.P...GAL.TA.VTPPS..ASS..TVSTVP...LDSWT..FNT..QPLFAH.R.RG.S..";


const aminoAcidsArray5 = aminoAcidsString5.split('.');


const resultNineToFourteen5 = aminoAcidsArray5.filter(sequence => sequence.length >= 9 && sequence.length < 15);
console.log('Protein #5')
console.table(resultNineToFourteen5);

const resultSixteenUp5 = aminoAcidsArray5.filter(sequence => sequence.length >= 16);
console.table(resultSixteenUp5);

const resultFifteen5 = aminoAcidsArray5.filter(sequence => sequence.length === 15);
console.table(resultFifteen5);

const aminoAcidsString6 = "MA..I.AGIAGD.LGS.V.GLV.AGANAINQ.VEFGYNQALQ.NSF.HDKDMLA.QVAATRQLQSDLI..REQALR.GGFSDTDAARGAIGAPMT.LVDWNGTRL.APGAMHTT.YSGRF.......P.......................S.G.P..S.T.S..S..PS...S.S..R...WV.........S....L.PFHP.ALR.AWGS..SSS.SS..ASTVDG.VLDSWTPAFNLKHQPLFARFHPRGASN.";


const aminoAcidsArray6 = aminoAcidsString6.split('.');


const resultNineToFourteen6 = aminoAcidsArray6.filter(sequence => sequence.length >= 9 && sequence.length < 15);
console.log('Protein #6')
console.table(resultNineToFourteen6);

const resultSixteenUp6 = aminoAcidsArray6.filter(sequence => sequence.length >= 16);
console.table(resultSixteenUp6);

const resultFifteen6 = aminoAcidsArray6.filter(sequence => sequence.length === 15);
console.table(resultFifteen6);

const aminoAcidsString7 = "MMMASKDVVA....S..NA..NN..I.SRLMAR.RG.GG.......IKI....MALGLIR.............PKQQRDRPPRT..EVQ..MGW.E.P.DQN.K.W.EL...EK..IL..N..WFDAGG.GP.TLP.T.ER............V.WSA..GVDLGV..LTTV.GP.WNMCPLPP.D.RN..PA.EP.IGDMIEFYEGHIYHYAIYIGQGKTIGVHSPQAAFSI.RITIHPI.AWWRVCY.P...QRLTYDQLKELENEPWPYAAITNNCYEFCC.VM.L.DTWLQRRLIS.GRF.HPTQ.WS..TPDFQQDSKLE.VRDAVLAAINGLVS.PFKN.L.KLKPLNVLNLLSNCDWTFMGVVE.IVLL.ELFGVFW.PPDVS.FIASLLPDFHLQGPEDLARDLVP.ILGGIGLAIGFTRDKVTKVMKSAVDGLRAATQLGQYGLEIFS.IKKYFFGGDQTEKTLKGIE.AVIDMEVLSST.VTQLVRDKQ.ARAYMNILDNEEEKARKLSVR.ADPHVVSSTNALISRISMARSALAKAQAEMT.R.RPVVIMMCGPPGIGKTKAAEHLAKRLANEIRPGGKVGLVPREAVDHWDGYHGEEVMLWDDYGMSKI.EDCNKLQAIADTAPLTLNCDRIENKGMQFVSDAIIITTNAPGPAPVDFVNLGPVCRRVDFLVYCSAPEVEQ.RRTSPGDT.ALKDCFK.DFSHLKMELAPQGGFDNQGNTPFGKGVMKPTTLNRLLIQAVALTMERQDEFQLQG..YDFD.DRVSAFT.LARANGLGL.SMA.LGKKLR.V.S.EGLKNAL.GYKI..C.I.WQ.R.Y.IESDG..V.IKE.....TP.QQ.I.TA.LALTRLRAARA.AYASC.QSAVTSILQ.AGSALVVNRAVKRMFGTRT....LEGP.KEH.CRVH.AKAAG.GPIGHDDVIERYGLCETEEEEE........P.A..EGKNKGKTKKGRGRK.NYNAFSRRGLSDEEYEYKKIREEK.GNYSIQEYLEDRQRYEEELAEVQAGGDGGIGETEMEIRHRVFYKSKSKK..QEERRQLGLVTGSDIRKRKPIDWTPPKN.WADDDREVDYNE.ISFEAPPTLWSRVVKFGSGWGFWVSPTVFITTTHVIP..AKE.FGE.L..IAIHRAGEFTQFRFSKK.RPDLTGMVLEEGCPEGTVCSILIKRDSGELLPLAVRMGAIASMKIQGRLVHGQSGMLLTGANAKGMDLGTIPGDCGAPYVHKR.NDWVVCGVHAAATKSGNTVVCAVQAGEGETTLEGGDKGHYAGHEIVRYG.GPALSTKTKFWKSTPEPLPPGVYEPAYLGGRDPRV.GGPSLQQVLRDQLKPFAEPRGRMPEPGLLEAAVETVTS.LEQVMDTPVPWSY.DACQSLDKTTSSG.PHHKRKNDDWNG..FVRELGEQAAHANNMYE.GK.MKP.YTAALKDELVKPEKVY.KIKKRLLWGADLGTVIRAARAFGPFCDAIKSHVIKLPIKVGMN.IEDGPLIYAEHSKYK.HFDADYTAWDSTQNRQIMTESFSIMCRLTASPELA.VVAQDLLAPSEMDVGDYVIRVKEGLPSGFPCTSQVNSINHWIITLCALSEVTGLSPDVIQSQSYFSFYGDDEIVSTDIEFDP.RLTQVLKEYGLKPTRPDKTEGPIIVR.QVDGLVFLRRTISKDAAGFQGRLDRASIERQL.WTRGPNH.DPFETLVPH.QRKVQLISLLGEASLHGEKFYRKIASRVIQEIKTGGLEMYVPGWQAMFRWMRFHDLGLWTGDRDLLPEFVNDDGV";


const aminoAcidsArray7 = aminoAcidsString7.split('.');


const resultNineToFourteen7 = aminoAcidsArray7.filter(sequence => sequence.length >= 9 && sequence.length < 15);
console.log('Protein #7')
console.table(resultNineToFourteen7);

const resultSixteenUp7 = aminoAcidsArray7.filter(sequence => sequence.length >= 16);
console.table(resultSixteenUp7);

const resultFifteen7 = aminoAcidsArray7.filter(sequence => sequence.length === 15);
console.table(resultFifteen7);

const aminoAcidsString8 = "MKMASNDA..A.A.....N...............F.N..VT.KK.LGARPK........................IPPPPPNGED.............I.GLP.LTTV.......TAYSVPPLS.RE...AKEPLPG.ILEMWDGEIYHYG.YV..G.VLGVHKPPAAISLA.IELTPLSLYWR.VYTP.YLV.P.TLK.L.GE.FPYTAF.NNCY.FCCWVLDLNDSWLSRR.I.RTTGFFRPYQ.WNRKPLPTMDD.KIKKVAN..LC.LSSLFTRPIKDL.GK.KPLNILNILA.CDWTFAGIVE.LIL.AELFG.FWTPPDVS.MIAPLLGDYELQGPEDLAVELVPVVMGGIGLVLGFT.EKIGKMLSSAASTLRACKDLG.YGLEILKLVMKWFFPKK.E.NELAMVRAIEDAVLD.EAIENNHMTTLLKDKDSL.TYMKTLDMEEEKARKLSTKSASPDIVGTINALLARIAAARSLVHRAKEELSSR.RPVV.MISGRPGIGKTH.AR..AK..A.TLSGDQRVGLVPRNGVDHWDAYKGERVVLWDDYGMSNPI.DALRLQELADTCPLTLNCDRIENKGK.FDSD.IIITTNL.NPAPLDYVNFEACSRRIDFLVYADAP.VEKAKRDFPGQPDMWKDAFK.DFSHIKL.LAPQGGFDKNGNTPHGKG.MKTLT..SL.ARA.GLLHER.DEF.LQG..L..FNFD.NKV.AFRQLAAENKYG.VET.KVG..LK.VKTLE.LK.A.R.V.IK.C.IIY....Y...SDG.G.V.V.KV....VQTNNEL..AL..LR.ARIRYYVKCFQE..YSLIQIAGAAFVT.RI..RM....LW.KP......................I.S.DI..EGKKGKNK.GRGKKHTAFSSKGLSDEEYDEYKRIREERNGKYSIEEYLQDRDRYYEELAIAKATEEDFCEEEE.KIRQRIFRPTRKQRKEERA.LGLVTGSEIRKRNPDDFKPKG.LWADD.RSVDYNEKLDFEAPPS.WSRIV.FGSGWGFWVSPSLFIT.THV.P.G..EAFGV.I.QIQIHKSGEFCR.RFPKPIRPDV.GMILEEGAPEGTV.S.LIKRPTGELMPLAARMGTHATMKIQGRMVGGQMGMLLTGSNAK.MDLGT.PGDCGCPYIYKRGND.VVIGVHTAAARGGNTVICATQG.EGEATLEG.D..GTYCGAPILGPG.APKLSTKTKFWRSSN.PLPPGTYEPAYLGGRDPRVKGGPSLQQVMRDQLKPFTEPRGKPP.P.VLE.AK.TI.NVLEQTI.PP.KWSYAQACASLDKTTSSG.PHH.RKND.WNGESFTG.LADQASKANLMYEEGKHM.PVYTAALKDELVKT.KIY.KIKKRLLWGSDLSTMIRCARAFGGLMDEMKA.C..LP.RVGMNMNEDGPIIFEKHSRYKYHYDADYSRWDSTQQR.VL.AALEIMVRFSAEPQLAQIVAEDLLAPSVVDVGDFKI.INEGLPSGVPCTSQWNSIAHWLLTLCALSEVT.LSPDVIQANSMFSFYGDDEIVSTDIKLDP.KLT.KLKEYGL.PTRPDKTEGPLVI.E.L.GLTFLRR.I.RDPAGWFGKLDQ.SILRQLYWTRGPNHEDP.ETMIPHSQRP.QLMALLGEASLHGP.FYSKVSKLVI.ELKEGGMDFYVPRQE.M.RWMRFSDLSTWEGDRNLAP.FVNEDGVE";


const aminoAcidsArray8 = aminoAcidsString8.split('.');


const resultNineToFourteen8 = aminoAcidsArray8.filter(sequence => sequence.length >= 9 && sequence.length < 15);
console.log('Protein #8')
console.table(resultNineToFourteen8);

const resultSixteenUp8 = aminoAcidsArray8.filter(sequence => sequence.length >= 16);
console.table(resultSixteenUp8);

const resultFifteen8 = aminoAcidsArray8.filter(sequence => sequence.length === 15);
console.table(resultFifteen8);

const aminoAcidsString9 = "MKMASNDASVA.S...T.ANN..T....GGVFANMKVG.KK.L.SK..P..VRP...GKP..TRPPD.....G.VRY.A..DTIEGLPDL.TAP.P..RQVKCVPPM.EREV..A.EPQTGSLLEMYDGSFYHYAIYIENGLVAGINRPSKALTTATVDVEPIGLWWRVVYTPPFSVSTSALYHLQGEKFPYNAFDNNCYNFCCQVLELDDCWMRRKYVQRTTGFFDPYQSWNPKPSQYVADSKLERVGDALLTALGALFSKPIKNIIGKLKPLNFLNLLSSCDWTF.GIVET.ILIAELFDVYWEPPDVT.FLMPLLDDFELQGPEDLAAEIVPIILGGIGMVVGFTAEKAGRLLSSAAATLRATKELGNYGLEIVKLVMKWFFPKKESDMN.MVRNIEDAVLDLEAVENNHITHLLKDKENMA.FLRTLDLEEEKARKLSTKAASPDIVASVNALLARIAAVRSLAFKAKEEMCARQRPVVVMISGRPGIGKTHYAR.LASRISKLL..DGRVGLVPRNGVDHWDAYRGEPVVVWDDYGMGNIIKDAMMLQELADTCPVTLNCDRIENKGKMFESDVIVLTTNSPNPSPMDYVNMEAVARRVDFLVYAESPEIEKAKRDFPGDPKAWKPHFKDDHSHLVLTLAPQGGFDK.GNTPHGKG.VKNITPNGLVARAVALAVERRDEFQLQG.EP.TYNFDSSQVAAFRKLAADNKYGLAETLRVGNKLR.VTTIEGFKKAVGDV.FKKCRIIWKGVTYDLESDGKGSV.IDRVQSQMVQTTGEIHQAVLRLRQARVRYYVMTAQNVVYGLLQAAGAAFVLNRIFRRAENPFSRM.KVE...D.P...P......KVEIV..D.EEEGKKKGKNKQGRGRKHTAFSSKGLSDEEYEEFKQIREERGGKYSIQEYLEDRDRFEEEVAYAQACGGDCDDIEISRIRNSIFRPSRKQRKEERVKLGLVTG.EIRKRKPDDFQPKGKLWADDDRTVDYNEKLDFEAPASIWARIVQLGTGWGFWVSPNLLITSTHVIPKGVEELFGVPI.QVQVH.CGEFTRLRFPKMIRPDVTGMILEDGAPEGVVCSILVKRPTGECLPLAVRMGTQATMKIQGKVVSGQLGMLLTGSNAKNMDLGTTPGDCGCPYVYKRGNDYVVVGVHTAAGRGGNTVICAVQT.DGEAVLEGN.DNGTYCGAPIVSKGNAPQLSTKTKFWRSSVEPLPPGTYEPAYLGGRDPRV..GPSLYQVMRDQLKHFTAPRGRPVKPHLLQAAVKTIENVLEQTIDPP.PWTYAQACQSLDKTTSSGWPHHVQKNTHWNGESFTGPLADQAS.ANLMYEQ.KSMTPQYTAALKDELVKP.KVY.KVKKRLLWGADLGTMVRCARAFGPFTDALKKCC..LP.KVGLNINEEGPIIFEKHSQYE.HYDADYSRWDSTQQREVLAAALGIMTKFTAEP.LAAVVAEDL.APSMLDVGDYVVQVNEGLPSGVPCTSQLNSIAHWI.TLTSMAEATGLDPDIVQANSYFSFYGDDEIVSTD.KFNPEVLTLKLKAVGLVPTRPDKTEGPLVVSRKLEGLTFLRRTITRDKVGFFGRLDKDSILRQLYWTKGPNHQDPSESMLPHQNRATQLMALLGESALHGQNFYKKVSGMVIKEIKNGGHEFYVPKFESMYKWMRFSDLSTWEGDRDLAPDYVNEDGVE";


const aminoAcidsArray9 = aminoAcidsString9.split('.');


const resultNineToFourteen9 = aminoAcidsArray9.filter(sequence => sequence.length >= 9 && sequence.length < 15);
console.log('Protein #9')
console.table(resultNineToFourteen9);

const resultSixteenUp9 = aminoAcidsArray9.filter(sequence => sequence.length >= 16);
console.table(resultSixteenUp9);

const resultFifteen9 = aminoAcidsArray9.filter(sequence => sequence.length === 15);
console.table(resultFifteen9);

